export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    darkText: false,
    topLine: 'Premium Bank',
    headline: 'Unlimited Transactions with zero fees',
    description: 'Get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees.',
    buttonLabel: 'Get started',
    imgStart: false,
    img: require('../../images/svg-3.svg'),
    alt: 'Car',
    dark: true,
    primary: true,
    derkText: false,
}

export const homeObjTwo = {
    id: 'discover',
    lightBg: true,
    lightText: false,
    darkText: true,
    topLine: 'Discover',
    headline: 'The best offers on the market  no additional or hidden fees',
    description: 'Get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees.',
    buttonLabel: "Don't Wait Get In",
    imgStart: false,
    img: require('../../images/svg-1.svg'),
    alt: 'Car',
    dark: true,
    primary: true,
    derkText: false,
}

export const homeObjThree = {
    id: 'services',
    lightBg: false,
    lightText: true,
    darkText: false,
    topLine: 'Services',
    headline: 'Unlimited Transactions with zero fees',
    description: 'Get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees.',
    buttonLabel: "We're here for you",
    imgStart: false,
    //img: require('../../images/svg-1.svg'),
    alt: 'Car',
    dark: true,
    primary: true,
    derkText: false,
}

export const homeObjFour = {
    id: 'signup',
    lightBg: true,
    lightText: false,
    darkText: true,
    topLine: 'Sign Up',
    headline: "Don't miss your chance sign up today and recieve $300 towards your credit account",
    description: 'Get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees.',
    buttonLabel: 'Sign Up',
    imgStart: false,
    //img: require('../../images/svg-1.svg'),
    alt: 'Car',
    dark: true,
    primary: true,
    derkText: false,
}